spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumerGroup: CustomerValidatedGroup
    topic:
      customerCreated: CUSTOMER_CREATED_TOPIC
      customerValidated: CUSTOMER_ACTIVATED_TOPIC
security:
  basic:
    enabled: false