spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/edircabsan/spring-netflix/
          search-paths:
            - "ms-config-properties/{application}/{profile}"