spring:
  kafka:
    bootstrap-servers: kafka-1:9092
    consumerGroup: CustomerValidatedGroup
    topic:
      customerCreated: CUSTOMER_CREATED_TOPIC
      customerActivated: CUSTOMER_ACTIVATED_TOPIC
security:
  basic:
    enabled: false